src/main/java/com/github/onsdigital/perkin/SurveyListener.java
Change current perkin env vars to better work with compose locally.
=> Change env vars to use rabbit docker image defaults

src/main/java/com/github/onsdigital/perkin/transform/TransformEngine.java, src/main/resources/templates/receipt.xml
Use auth headers and use correct collection type.
=> Update to use statistical id

README.md
=> Update travis links to new lowercased github repo

src/main/java/com/github/onsdigital/perkin/helper/Http.java
Temporarily disabling ssl verification for end-to-end test.
=> Disable ssl verification

Dockerfile
**Changes**
Update to use standard java docker vs onsdigitals one
See if it builds
=> Update dockerfile to use standard java image

src/main/java/com/github/onsdigital/HttpManager.java, src/main/java/com/github/onsdigital/perkin/SurveyListener.java
noticed a public constructor in a singleton class - made it provate so have to use getInstance()
queue connection should now retry if it gets shutdown
=> Queue connection

src/main/java/com/github/onsdigital/perkin/SurveyListener.java
Releasing queue connection fix to preprod.
=> Flush queue connection fix

src/main/java/com/github/onsdigital/perkin/SurveyListener.java
**Changes**
- Remove current shutdown handling
- Switch on rabbits auto recovery mode
- Force a rabbit shutdown and restart and see if perkin recovers
=> Let rabbit handle network recovery

src/main/java/com/github/onsdigital/perkin/transform/NumberService.java, src/test/java/com/github/onsdigital/perkin/test/ParameterizedTestHelper.java, src/test/java/com/github/onsdigital/perkin/transform/NumberServiceTest.java
Stores batch sequence numbers to disk to prevent overwriting of data.
=> Avoiding batch number reset.

src/main/java/com/github/onsdigital/perkin/transform/NumberService.java, src/test/java/com/github/onsdigital/perkin/transform/NumberServiceTest.java
Sorted out looping a sequence round to the start value when saved out to a .sequence file.
Check that the sequence number loops correctly when saved and reloaded at each increment.
=> Sequence number looping via saved .sequence file

src/main/java/com/github/onsdigital/perkin/decrypt/Decrypt.java, src/test/java/com/github/onsdigital/perkin/services/DecryptTest.java
at the moment, you can post plain json e.g.
{ test="now" }
onto the queue and decryption via posie will be skipped.
this change will mean all queued messages will be treated the same and the contents decrypted via posie
=> disable plain text json support

.travis.yml, Dockerfile, src/main/resources/log4j.xml, src/test/resources/log4j.xml
Creates config variables for setting log levels in different builds. Set the log4j log level you want for com.github.onsdigital logging using the LOG_LEVEL parameter and the root level logging with ROOT_LOG_LEVEL.
=> Adding dockerfile logging level control

Dockerfile, startup.sh
**Changes**
- Set default logging level for current logging properties in startup script.
- Startup with no environment variables, check verbosity of messages
- Startup with ROOT_LOG_LEVEL/LOG_LEVEL variables, check verbosity of messages is correct
=> Set some log defaults

src/main/java/com/github/onsdigital/perkin/SurveyListener.java, src/main/java/com/github/onsdigital/perkin/decrypt/Decrypt.java
make errors discoverable from splunk
log the encrypted data at info level (was debug)
log a warning if decryption fails
=> tweak logging so can see data we tried to decrypt

src/main/java/com/github/onsdigital/perkin/transform/TransformEngine.java, src/main/java/com/github/onsdigital/perkin/transform/idbr/IdbrTransformer.java, src/main/java/com/github/onsdigital/perkin/transform/jpg/ImageTransformer.java, src/main/java/com/github/onsdigital/perkin/transform/pck/PckTransformer.java, src/test/java/com/github/onsdigital/perkin/transform/idbr/IdbrTransformerTest.java, src/test/java/com/github/onsdigital/perkin/transform/jpg/ImageTransformerTest.java, src/test/java/com/github/onsdigital/perkin/transform/pck/PckTransformerTest.java
uses a future task (thread) for each transformation
how to test
process a survey, all files should be produced (but a little quicker)
who can test
anyone but dave gunthorpe
=> mutltithreaded transformations

README.md
documentation update - please check the readme is now correct
testing - anyone but david gunthorpe
=> change perkin to sdx-collect

app/async_consumer.py, app/consumer.py, app/receipt.py, app/response_processor.py, tests/test_receipt.py, tests/test_response_processor.py
**Changes**
Add tx_id to log messages if within decrypted payload.
Use within sdx-compose setup and check that log messages include tx_id.
=> Add tx_id to bound logger

app/async_consumer.py
Same fix that got applied to sdx-downstream
=> Fix logging to use structlog format

app/settings.py
**Changes**
Removed the extra config for the third rabbit queue
=> remove third queue

.gitignore, Makefile
Updates .gitignore to exclude `virtualenv` files from git.
Also adds Makefile to make build and test easier
=> Update .gitignore and add Makefile

README.md
Added SDX_COLLECT_SECRET to readme.
=> Add additional environment variables to project readme.

app/async_consumer.py
Was somehow missing the `nack` method
=> Add missing nack method to async consumer

app/response_processor.py
This commit changes the logging parameters from status_code to status for Splunk to correctly pick up logged messages.
=> Changes status_code to status

CHANGELOG.md, app/response_processor.py, tests/test_response_processor.py
Change 'calling service' and 'returned from service' logging messages to add context.
=> Change service msg

Dockerfile, Makefile, README.md
> What does this pull request change/fix? Why was it nessessary?
Fixes make dev issue with clean environments 
https://trello.com/c/5UZdTQJa/210-make-files-dont-work-in-clean-environments-2
=> Replacing make dev with make build

.gitignore
> What does this pull request change/fix? Why was it nessessary?
Updated git ignore
=> Consistency Update

CHANGELOG.md, Dockerfile
Remove sdx common clone in Dockerfile
=> Remove sdx-common clone in Dockerfile

Dockerfile, Makefile
Fix docker build. Has been tested.
=> Fix cryptography install

app/settings.py
=> Update default name for downstream queue

CHANGELOG.md, app/__init__.py, app/response_processor.py, app/settings.py, config.ini
Add all service config to config file. This should mean easier to modify config.
=> Add config file

CHANGELOG.md, app/__init__.py
=> Update version number

CHANGELOG.md, app/response_processor.py, tests/test_data.py, tests/test_response_processor.py
Added if statement to check if invalid and its not a feedback survey - (https://github.com/ONSdigital/sdx-collect/issues/217 )
=> Fixes incorrect logging if validation fails #217

CHANGELOG.md, app/__init__.py
=> Update changelog and version

Dockerfile
=> Remove unnecessary steps in dockerfile

manifest.yml
Fix the environment variable name for Cloudfoundry
=> Fix env variables for CF

mainfest-template.yml
Adding manifest template for jenkins
=> Add manifest template for collect

manifest-template.yml
> What does this pull request change/fix? Why was it necessary? Standardises the Rabbit queue name across CF environments
=> Standardise Rabbit queue name across CF environments

CHANGELOG.md, app/response_processor.py, tests/test_data.py, tests/test_response_processor.py
Sends JSON with `case_id` key to rrm-receipt queue
=> Add case_id to json for surveys originating from RM

CHANGELOG.md, app/__init__.py
> Release branch for release 3.5.0
=> Release 3.5.0

CHANGELOG.md, app/__init__.py
=> Update version and changelog

CHANGELOG.md, app/main.py
[trello](https://trello.com/c/P4jSIIfy/2504-ensure-all-sdx-services-log-their-version-on-startup)
=> Add version log on startup

CHANGELOG.md, Dockerfile, app/response_processor.py
=> Send D-Trades to DAP

CHANGELOG.md, app/response_processor.py, tests/test_data.py, tests/test_response_processor.py
Updating response processor to send census data to dap. This is for census Hannah 0.1
=> Updating response processor to send census data to dap

CHANGELOG.md, app/__init__.py
Updating changelog and version to 3.12.0
=> Updating changlog and version

CHANGELOG.md, app/response_processor.py
As part of some other work to log if the survey wasn't processed (not needed, already done by sdx-validate), I noticed that f-strings weren't being used and that the remote call function has arguements that aren't used.  
This PR just tidies the code up a bit to make it easier to read
=> Tidy formatting and function arguments

CHANGELOG.md, app/response_processor.py
=> Add corvid-19 survey to DAP bound surveys

CHANGELOG.md, app/__init__.py
=> release 3.19.1

CHANGELOG.md, app/__init__.py
=> update version number to 3.19.2

CHANGELOG.md, app/response_processor.py
> MWSS now needs to go to DAP as well as downstream, for the extra questions to be processed.
=> MWSS added to list of surveys requiring DAP processing

CHANGELOG.md, app/__init__.py
=> update version number to 3.20.0

CHANGELOG.md, app/response_processor.py
> Add EPE to DAP processing list
=> Add EPE survey

CHANGELOG.md, app/response_processor.py, tests/test_data.py, tests/test_response_processor.py
functions to automate feedback saving and collection for downstream processing
- [ X ] CHANGELOG.md updated? (if required)
=> Sdx feedback automation

CHANGELOG.md, app/response_processor.py, tests/test_data.py, tests/test_response_processor.py
- [ X ] CHANGELOG.md updated? (if required)
=> changes in changelog, names, tests

CHANGELOG.md, app/response_processor.py
=> Low carbon
