ONSdigital/sdx-collect

- src/main/java/com/github/onsdigital/perkin/json/Metadata.java
- src/main/java/com/github/onsdigital/perkin/transform/TransformEngine.java
- src/main/java/com/github/onsdigital/perkin/transform/idbr/IdbrTransformer.java
- src/main/java/com/github/onsdigital/perkin/transform/jpg/ImageIndexCsvCreator.java
Rename the current respondent id methods to avoid confusion with downstream systems use of respondent id (where the term means a responding user_id). getRuRefId could be refactored further to getStatisticalUnitId, but is probably unnecessary for us.
This tallies with Rachels investigation of term differences between each of the components.
> Refactor respondent id methods

- src/main/java/com/github/onsdigital/perkin/json/Metadata.java
- src/main/java/com/github/onsdigital/perkin/transform/TransformEngine.java
- src/main/java/com/github/onsdigital/perkin/transform/idbr/IdbrTransformer.java
- src/main/java/com/github/onsdigital/perkin/transform/jpg/ImageIndexCsvCreator.java
Use the "StatisticalUnitId" as a metadata method to retrieve ru ref without checkletter appended, rather than ru ref id, which will mostly likely confuse things further down the line.
Additionally, correct the call to rrm to use this method, rather than the full ru ref.
> Correct call to RRM and refactor method

- src/main/java/com/github/onsdigital/ConfigurationManager.java
- src/main/java/com/github/onsdigital/perkin/helper/TemplateLoader.java
- src/main/java/com/github/onsdigital/perkin/json/Survey.java
- src/main/java/com/github/onsdigital/perkin/json/SurveyTemplate.java
- src/main/java/com/github/onsdigital/perkin/transform/TransformEngine.java
- src/test/java/com/github/onsdigital/perkin/helper/TemplateLoaderTest.java
- src/test/java/com/github/onsdigital/perkin/json/SurveyTest.java
In order to write some meaningful tests for sending a RRM receipt, I've refactored some of my previous work and current methods for template loading.
Points of note:
- I've moved the sendReceipt call to rrm into the survey class itself. This enables me to test the attributes of the receipt without having to load/mock up all the dependencies within the transform engine that it was previously a part of.
- I've refactored template loading into a globally available TemplateLoader which can be pulled in from anywhere, removing the behaviour from TransformEngine. I've added the start of some tests for this. 
- I've added a configuration manager "setter" method in order to be able to set environment variables within our tests, rather than only being to load them from the environment. 
Creating …
> Refactor to better enable testing

- src/main/java/com/github/onsdigital/perkin/helper/FileHelper.java
- src/main/java/com/github/onsdigital/perkin/json/Survey.java
- src/test/java/com/github/onsdigital/perkin/services/ReceiptTest.java
Don't re-queue receipt failures, rather log the error for splunk to pick up and handle.
> Log receipt failures rather than requeue

- src/main/java/com/github/onsdigital/perkin/decrypt/Decrypt.java
- src/main/java/com/github/onsdigital/perkin/helper/Http.java
- src/main/java/com/github/onsdigital/perkin/json/Survey.java
**Changes**
- Remove decrypted survey logging / HTTP response body logging (Both expose raw decrypted json)
- Explicitly log successful calls to RRM
- Run on aws environment and check whether payloads appear in logs
- Run on preprod and ensure successful receipts are logged
> Don't log body of HTTP responses

- src/main/java/com/github/onsdigital/perkin/SystemInfo.java
- src/main/resources/env.properties
Added build identification information, passed through from Jenkins. The variables logged are: GIT_URL, GIT_BRANCH, GIT_COMMIT, BUILD_TAG, BUILD_URL. These will be logged with the message "Build identification" so Splunk can find the lines.
Start up Perkin and look for "Build identification" log lines that contain GIT_URL, GIT_BRANCH, GIT_COMMIT, BUILD_TAG, BUILD_URL. Test values can be passed in using -e options on the Docker command-line.
Anyone but @davidcarboni
> Build identification

- src/main/java/com/github/onsdigital/perkin/SurveyListener.java
splunk caused the queue to fail by testing the queue connection every 60 secs. this should fix it, we were closing the channel and not the connection. closing the connection is supposed to close all channels as well as the connection
> close connection, not channel

- src/main/resources/log4j.xml
Changing log4j config to create a persistent log file.
To Test locally
Locally we can test that the file is being produced. Once merged into the amazon environment we can then see if the file is created in the correct place.
Locally do a mvn clean install and then navigate to the target directory and run:
java -jar Perkin-0.0.1-SNAPSHOT-jar-with-dependencies.jar
If the config has worked correctly you should see a perkin.log file appear in the target/logs.
Once merged, the amazon environment already has the volume setup and so we should be able to ssh to the machine and see the log file in home/ubuntu/edc/logs.
> Changing log4j config to log to persistent log location

- .gitignore
Added logs/ to .gitignore as this folder is getting created when building Perkin as a submodule in the Dockers project (https://github.com/ONSdigital/dockers).
Need to get this merged in and updated into master to see if the Perkin submodule will no longer show as "dirty" after a build.
Anyone but @davidcarboni
> Added logs/ to gitignore

- README.md
- src/main/resources/env.properties
Checked through the Perkin codebase for references to Posie.
These now point to sdx-decrypt instead.
Ensure everything runs correctly in the docker-compose setup.
Anyone but @davidcarboni
> Removed references to Posie in favour of sdx-decrypt.

- src/main/resources/env.properties
so it can be overriden
to test:
set jenkins value to false for WRITE_BATCH_HEADER, check logs that value has been set correctly to false
who can test:
anyone but david gunthorpe
> add WRITE_BATCH_HEADER to env.properties

- src/main/java/com/github/onsdigital/perkin/SurveyListener.java
**Changes**
Make the listener attempt to create a durable queue in line with recent changes to preprod queue.
I've tested this branch on preprod already, confirmed to now be connected to queue and processing.
> Rabbit durable

- app/async_consumer.py
**Changes**
A recent eQ change has been to make the eQ queue durable, which also needs to be declared on the client side. This pull request adds this setting to the `queue_declare` call.
- Clean sdx-compose build with durable-queue branches for sdx-collect, sdx-console and sdx-bdd
- Run some surveys through the console
- Run sdx-bdd 
- Check the queue is marked as durable in the RabbitMQ UI
Anyone but @ajmaddaford
> Make queue durable in queue_declare

- app/templates/receipt.xml.tmpl
- tests/test_receipt.py
- tests/xml/receipt_no_txid.xml
- tests/xml/receipt_txid.xml
The spaces before `<receipt_type>` and `<respondent_id>` weren't real spaces (each space was a byte sequence of 342 200 202). This commit replaces them with real spaces.
> Replace odd spaces with real spaces in mock receipt template

- app/receipt.py
- app/response_processor.py
- tests/test_receipt.py
**Changes**
- Fix statistical unit id in receipt service URL
- Fix basic auth - now uses Python requests library built in auth method rather than constructing the auth header manually
- Turn off SSL certificate verification for receipt service call to workaround issue with the receipt service SSL certificate
- Run the sdx-compose setup
- Check out the mock-auth branch for the sdx-mock-receipt repo
- Check that receipt service calls fail with 401 authentication error
- Check out the add-receipt-service-auth branch for the sdx-compose repo
- Check that receipt service calls succeed with a 201 status
Anyone but @ajmaddaford
> Fix receipt service call

- app/async_consumer.py
- app/consumer.py
- app/queue_publisher.py
- app/settings.py
**Changes**
Uses a dead letter queue with a ttl on the messages to provide delayed retries functionality. See
http://stackoverflow.com/questions/17014584/how-to-create-a-delayed-queue-in-rabbitmq.
Also uses a 'x-delivery-count' header to keep track of how many times a message has been attempted and limit the number of attempts at re-processing. 
Note that we still don't consider whether an error is retry-able or not - we just naively attempt to re-process a message up to three times. That will need to be done in a future pull request. 
- Run the sdx-compose setup
- Submit a survey and ensure outputs are generated
- Remove the survey_id from a survey and submit
- Check logs or rabbitmq web UI to see messages written to the survey_delay queue and after a 20 second delay …
> Use dead letter queue and a count to provide retry functionality

- app/response_processor.py
- tests/test_response_processor.py
This allows invalid submissions to be stored in the db rather than logged out.
https://github.com/ONSdigital/sdx-validate/pull/14
https://github.com/ONSdigital/sdx-store/pull/14
> Add invalid indicator for storage when validation has failed

- app/helpers/exceptions.py
- app/response_processor.py
Before there was very little logging describing which queue was being published too. This commit adds this
and also puts the tx_id as a field for easier searching.
> Add more logging around receipts

- app/response_processor.py
When doing something as large as decrypting, validating or storing, there should be matching 'I'm about to do X' and 'X was successful'
This commit puts in the latter messages
> Added missing logging around key points

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
Only receipt if the Survey data is valid. I believe this is part of the reason we had a message endlessly nacking around the system. The test data was missing a survey id, so validation failed with a 500 which caused collect to error when it attempted to get the survey id. The whole thing then gets repeatably re-attempted. There is an associated sdx-validate change with this.
> Receipt a survey only if the JSON is valid

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
This pull request alters the process for dealing with a CTP submission to collect. Instead of receipting, a CTP submission will now cause the logline "Ignoring received CTP submission" to be emitted, and no further processing of the submission will take place.
> Do not process ctp submissions. Log at info the fact that a ctp submission was received

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
Previous code could hang on http error after urllib retries with heartbeat still working only corrected by a restart.
Now http errors will raise a RetryableError leading to a NAK and retry . 
-  CHANGELOG.md updated
> Retry handling

- CHANGELOG.md
- app/settings.py
Updating the default queue value so that it uses the sdx-gateway locally in docker compose.
> Set collect default queue value to the new sdx-gateway queue

- CHANGELOG.md
- requirements.txt
> What does this pull request change/fix? Why was it necessary? Remove sdx-common from requirements as it is no longer used.
> Remove sdx-common requirement

- runtime.txt
Python 3.6.1 no longer exists in cloud foundry
> Updating cloud foundry python

- CHANGELOG.md
- app/response_processor.py
- tests/test_data.py
- tests/test_response_processor.py
Support LMS test 1, this survey should only be stored in the database and not send to downstream for transformation and processing.
> Support LMS test 1 surveys

- CHANGELOG.md
- app/__init__.py
- Support LMS test 1 by skipping downstream
> Release 3.6.0

- CHANGELOG.md
- app/settings.py
- tests/test_settings.py
In moving to AWS corp, there aren't 2 rabbit URLs to hit, there is 1 url that load balances between rabbit clusters.
> Remove 2nd host

- app/response_processor.py
The `version` field in the dap message needed to not have the 'v' prefix.  This removes it.
> Amend json being sent to dap queue

- CHANGELOG.md
- app/response_processor.py
All feedback surveys shouldn't be processed.  The LMS ones were as the check wasn't checking if it was a feedback survey or not.
https://trello.com/c/fqqVuRhm/2549-stop-lms-feedback-surveys
Put through a feedback submission through sdx. It should only be stored in the feedback responses table, with log lines saying it's skipping processing on account of it being a feedback survey.
> Don't process lms feedback submissions

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
https://trello.com/c/fRBkb2xA/753-copy-rsi-data-and-send-to-dap-as-a-dtrades-submission-2
RSI submissions need to go to DAP as well as to common software.
Submit an RSI survey via console.  Make sure that it ends up in both the FTP folder and ends up on the DAP queue in rabbit (you can see it via the management console)
> Send rsi submissions to dap as well as downstream

- CHANGELOG.md
- app/response_processor.py
- requirements.txt
There was a bug where every submission after the first would have the previous submissions tx_id in the logs between the start and after the decryption.  After the decryption, the correct one became bound.  This fixes that issue.
Additionally updates urllib3 to fix a security vulnerability.
- Check out master
- Put through 2 submissions.  You'll notice on the second submission there are references to the first submissions tx_id, user_id and ru_ref in the first few lines (around the time being decrypted)
- Check this branch out
- Put through 2 more submissions and notice that the incorrect data is not there anymore.
> Investigate extra sdx decrypt lines after submissions

- CHANGELOG.md
- app/settings.py
- tests/test_settings.py
> Heartbeat was occurring too frequently leading to noise in the logs . By removing the override it now heartbeats every 30 seconds which is agreed to be sufficient
- [x ] CHANGELOG.md updated? (if required)
> 995 revert to default heartbeat

- .travis.yml
- CHANGELOG.md
Add python 3.8 to travis builds so we can have confidence in our system when we end up upgrading the version of python we use
> Add python 3.8 to travis build

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
If a submission had a null character in it, it would fail to save to store, get put back on the queue, then loop infinitely.
This PR makes it so that if there is a null character in a submission data (feedback and 1.0.0) then it gets quarantined
> Strip null character

- CHANGELOG.md
- app/response_processor.py
- tests/test_response_processor.py
There was a fix put in place to handle submissions with invalid characters.  This didn't work, so another better fix has been put in place.
- Spin up the sdx services in sdx-compose with sdx-validate, sdx-collect and sdx-store on the handle-invalid-chars branch.
- In sdx-console, submit a 009.0201, but not before changing 146h to include the string \u0000 (this can be anywhere in the string)
- Submit this, it should be put in the quarantine queue (view in management console on localhost:15672) and there should be some error logging to reflect this in store and collect
> Better handle submissions with invalid characters

- CHANGELOG.md
- Dockerfile
- app/response_processor.py
- reprocess.py
> Allows the reprocessing of decrypted submissions
> Pull the code and run with sdx-compose. Find the id of the container for sdx-collect (using docker ps) and then
use "docker exec -it <container id> /bin/bash" to ssh into it. Create a file for a json submission (e.g. test.json) and then call
"python reprocess.py test.json". Exit the container ("exit") and log into the sdx-console and confirm that all of the associated artefacts have been correctly created (pck etc) or log into the rabbit console to confirm that a message was put on the dap queue (if survey requires dap processing).
> Reprocessing script

- CHANGELOG.md
- app/response_processor.py
> Ensures feedback for 283 gets sent downstream
> Feedback for 283
